//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Modnica.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime OrderCheckDate { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public Nullable<int> OrderClient { get; set; }
        public string OrderComment { get; set; }
        public int OrderStatus { get; set; }
        public int OrderManager { get; set; }
        public int OrderPoint { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Point Point { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
